### PR TITLE
add support for drawing dynamic matrix

### PR DESCRIPTION
**Pull request by dubcyfor3**

### CODE REVIEW

**Comment by fuvty** [comment]
@dubcyfor3 Could you give an example of how to draw the dynamic matrix in `example/visualization/dynamic_matrix.py`, please? You may want to sync with the main branch before working on that.

**Review by fuvty — COMMENTED** [review]
Great! An working example would be better.

**Comment by dubcyfor3** [comment]
I have added an example of using DynamicAdjacencyMatrix to draw a dynamic matrix gif.

**Comment by fuvty** [comment]
Terrific, thanks for the contribution.

**Pull request merged**
